// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: M5Core2_SFB

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BGmainS1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BGmainS1, 320);
    lv_obj_set_height(ui_BGmainS1, 240);
    lv_obj_set_align(ui_BGmainS1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BGmainS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BGmainS1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BGmainS1, lv_color_hex(0x723232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BGmainS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BGmainS1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleS1 = lv_label_create(ui_BGmainS1);
    lv_obj_set_width(ui_TitleS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleS1, 0);
    lv_obj_set_y(ui_TitleS1, -95);
    lv_obj_set_align(ui_TitleS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleS1, "Status");
    lv_obj_set_style_text_color(ui_TitleS1, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleS1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenSwitchS1 = lv_btn_create(ui_BGmainS1);
    lv_obj_set_width(ui_ScreenSwitchS1, 55);
    lv_obj_set_height(ui_ScreenSwitchS1, 125);
    lv_obj_set_x(ui_ScreenSwitchS1, 125);
    lv_obj_set_y(ui_ScreenSwitchS1, 0);
    lv_obj_set_align(ui_ScreenSwitchS1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenSwitchS1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScreenSwitchS1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenSwitchS1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenSwitchS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSwitchS1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenSwitchS1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScreenSwitchS1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScreenSwitchS1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArrowS1 = lv_label_create(ui_BGmainS1);
    lv_obj_set_width(ui_ArrowS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArrowS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArrowS1, 140);
    lv_obj_set_y(ui_ArrowS1, 0);
    lv_obj_set_align(ui_ArrowS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArrowS1, ">");
    lv_obj_set_style_text_color(ui_ArrowS1, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArrowS1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArrowS1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BGStatus = lv_obj_create(ui_BGmainS1);
    lv_obj_set_width(ui_BGStatus, 200);
    lv_obj_set_height(ui_BGStatus, 170);
    lv_obj_set_x(ui_BGStatus, 0);
    lv_obj_set_y(ui_BGStatus, 15);
    lv_obj_set_align(ui_BGStatus, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BGStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BGStatus, lv_color_hex(0x920924), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BGStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp = lv_label_create(ui_BGStatus);
    lv_obj_set_width(ui_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp, -43);
    lv_obj_set_y(ui_Temp, -60);
    lv_obj_set_align(ui_Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp, "Temperatur:");
    lv_obj_set_style_text_color(ui_Temp, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Com = lv_label_create(ui_BGStatus);
    lv_obj_set_width(ui_Com, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Com, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Com, -43);
    lv_obj_set_y(ui_Com, 60);
    lv_obj_set_align(ui_Com, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Com, "Com Status:");
    lv_obj_set_style_text_color(ui_Com, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Com, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempVal = lv_label_create(ui_BGStatus);
    lv_obj_set_width(ui_TempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempVal, 40);
    lv_obj_set_y(ui_TempVal, -60);
    lv_obj_set_align(ui_TempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempVal, "100°C");
    lv_obj_set_style_text_color(ui_TempVal, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ComValGreen = lv_obj_create(ui_BGStatus);
    lv_obj_set_width(ui_ComValGreen, 15);
    lv_obj_set_height(ui_ComValGreen, 15);
    lv_obj_set_x(ui_ComValGreen, 40);
    lv_obj_set_y(ui_ComValGreen, 60);
    lv_obj_set_align(ui_ComValGreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ComValGreen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ComValGreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_ComValGreen, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ComValGreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ComValGreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ComValRed = lv_obj_create(ui_BGStatus);
    lv_obj_set_width(ui_ComValRed, 15);
    lv_obj_set_height(ui_ComValRed, 15);
    lv_obj_set_x(ui_ComValRed, 40);
    lv_obj_set_y(ui_ComValRed, 60);
    lv_obj_set_align(ui_ComValRed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ComValRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ComValRed, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ComValRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ComValRed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BG_Flow = lv_obj_create(ui_BGStatus);
    lv_obj_set_width(ui_BG_Flow, 170);
    lv_obj_set_height(ui_BG_Flow, 80);
    lv_obj_set_x(ui_BG_Flow, -5);
    lv_obj_set_y(ui_BG_Flow, 0);
    lv_obj_set_align(ui_BG_Flow, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BG_Flow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BG_Flow, lv_color_hex(0x6D5338), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BG_Flow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SollFlow = lv_label_create(ui_BG_Flow);
    lv_obj_set_width(ui_SollFlow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SollFlow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SollFlow, -55);
    lv_obj_set_y(ui_SollFlow, 0);
    lv_obj_set_align(ui_SollFlow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SollFlow, "- Soll:");
    lv_obj_add_flag(ui_SollFlow, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_SollFlow, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SollFlow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IstFlow = lv_label_create(ui_BG_Flow);
    lv_obj_set_width(ui_IstFlow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IstFlow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IstFlow, -60);
    lv_obj_set_y(ui_IstFlow, 19);
    lv_obj_set_align(ui_IstFlow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IstFlow, "- Ist:");
    lv_obj_set_style_text_color(ui_IstFlow, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IstFlow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SollFlowMan = lv_label_create(ui_BG_Flow);
    lv_obj_set_width(ui_SollFlowMan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SollFlowMan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SollFlowMan, -39);
    lv_obj_set_y(ui_SollFlowMan, 0);
    lv_obj_set_align(ui_SollFlowMan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SollFlowMan, "- Manuell:");
    lv_obj_set_style_text_color(ui_SollFlowMan, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SollFlowMan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SollFlowManVal = lv_label_create(ui_BG_Flow);
    lv_obj_set_width(ui_SollFlowManVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SollFlowManVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SollFlowManVal, 40);
    lv_obj_set_y(ui_SollFlowManVal, 0);
    lv_obj_set_align(ui_SollFlowManVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SollFlowManVal, "50lpm");
    lv_obj_set_style_text_color(ui_SollFlowManVal, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SollFlowManVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IstFlowVal = lv_label_create(ui_BG_Flow);
    lv_obj_set_width(ui_IstFlowVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IstFlowVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IstFlowVal, 40);
    lv_obj_set_y(ui_IstFlowVal, 20);
    lv_obj_set_align(ui_IstFlowVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IstFlowVal, "50lpm");
    lv_obj_set_style_text_color(ui_IstFlowVal, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IstFlowVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SollFlowVal = lv_label_create(ui_BG_Flow);
    lv_obj_set_width(ui_SollFlowVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SollFlowVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SollFlowVal, 40);
    lv_obj_set_y(ui_SollFlowVal, 0);
    lv_obj_set_align(ui_SollFlowVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SollFlowVal, "50lpm");
    lv_obj_add_flag(ui_SollFlowVal, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_SollFlowVal, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SollFlowVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FlowTitle = lv_label_create(ui_BG_Flow);
    lv_obj_set_width(ui_FlowTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FlowTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FlowTitle, -59);
    lv_obj_set_y(ui_FlowTitle, -23);
    lv_obj_set_align(ui_FlowTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FlowTitle, "Flow:");
    lv_obj_set_style_text_color(ui_FlowTitle, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FlowTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_FlowTitle, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RCmode = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_RCmode, 50);
    lv_obj_set_height(ui_RCmode, 25);
    lv_obj_set_x(ui_RCmode, -119);
    lv_obj_set_y(ui_RCmode, -94);
    lv_obj_set_align(ui_RCmode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RCmode, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_RCmode, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags


    lv_obj_add_event_cb(ui_ScreenSwitchS1, ui_event_ScreenSwitchS1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RCmode, ui_event_RCmode, LV_EVENT_ALL, NULL);

}
